### ISSUE TITLE
PublishPipelineArtifact fails with symlink-related errors on self-hosted agent

### ISSUE THREAD

**Issue by rmetzger** [rmetzger/azure-pipelines-work#1]
https://dev.azure.com/rmetzger/Flink/_build/results?buildId=2465&view=logs&j=0b6f4d73-b90a-5b0c-8dd2-0a6ffa85c3c4&t=5d4dc765-6b4f-5976-543d-b9f12212f10f

```
2019-11-22T17:08:37.6778921Z ##[section]Starting: PublishPipelineArtifact
2019-11-22T17:08:37.6782304Z ==============================================================================
2019-11-22T17:08:37.6782403Z Task         : Publish Pipeline Artifacts
2019-11-22T17:08:37.6782501Z Description  : Publish (upload) a file or directory as a named artifact for the current run
2019-11-22T17:08:37.6782579Z Version      : 1.2.1
2019-11-22T17:08:37.6782664Z Author       : Microsoft Corporation
2019-11-22T17:08:37.6782742Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2019-11-22T17:08:37.6782852Z ==============================================================================
2019-11-22T17:08:38.1163492Z Artifact name input: FlinkCompileCacheDir
2019-11-22T17:08:38.1418904Z Uploading pipeline artifact from /home/agent/_work/1/flink_cache for build #2465
2019-11-22T17:08:40.4244761Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 3a398cea-fe82-4283-b172-34a9e4499501
2019-11-22T17:08:40.4526543Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 3a398cea-fe82-4283-b172-34a9e4499501
2019-11-22T17:08:42.1855979Z Information, 104208 files to be processed in 1043 groups.
2019-11-22T17:08:43.2454325Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/node-sass
2019-11-22T17:08:43.2457561Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/sassgraph
2019-11-22T17:08:43.2458298Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/node-gyp
2019-11-22T17:08:44.2273378Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/not-in-install
2019-11-22T17:08:44.2316317Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/not-in-publish
2019-11-22T17:08:44.2375963Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/strip-indent
2019-11-22T17:08:44.2855040Z Error, Failed to hash a page of files. Exception listed below...
2019-11-22T17:08:44.3384726Z Error, System.IO.FileLoadException: Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior. ---> System.IO.FileNotFoundException: Could not find file '/home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/sassgraph'.
2019-11-22T17:08:44.3385288Z File name: '/home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/sassgraph'
2019-11-22T17:08:44.3385452Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-11-22T17:08:44.3385646Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-11-22T17:08:44.3385749Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-11-22T17:08:44.3389313Z    at Microsoft.VisualStudio.Services.Content.Common.FileStreamUtils.OpenFileStreamForAsync(String filePath, FileMode mode, FileAccess fileAccess, FileShare fileShare, FileOptions extraOptions)
2019-11-22T17:08:44.3391148Z    at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.CreateFromFileAsync(IFileSystem fileSystem, String path, CancellationToken cancellationToken, Boolean configureAwait)
2019-11-22T17:08:44.3391602Z    at Microsoft.VisualStudio.Services.BlobStore.Common.FileBlobDescriptor.CalculateAsync(IFileSystem fileSystem, String rootDirectory, Boolean chunkDedup, String relativePath, FileBlobType fileBlobType, CancellationToken cancellationToken)
2019-11-22T17:08:44.3392619Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
2019-11-22T17:08:44.3393627Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
2019-11-22T17:08:44.3394385Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass25_0.<<PaginateAndProcessFilesHelperAsync>b__0>d.MoveNext()
2019-11-22T17:08:44.3395045Z --- End of stack trace from previous location where exception was thrown ---
2019-11-22T17:08:44.3395213Z    at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
2019-11-22T17:08:44.3395478Z --- End of stack trace from previous location where exception was thrown ---
2019-11-22T17:08:44.3395888Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.PaginateAndProcessFilesHelperAsync(String sourceDirectory, Boolean chunkDedup, IEnumerable`1 pathsInDir, Action`1 hashCompleteCallback, Int32 currentPage, Int32 totalPages, CancellationToken cancellationToken)
2019-11-22T17:08:44.3396108Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass22_0.<<PaginateAndProcessFiles>b__1>d.MoveNext()
2019-11-22T17:08:46.4874561Z Error, Failed to calculate hash for the file's reparse point: /home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/nopt
2019-11-22T17:08:47.5320107Z Error, Failed to hash a page of files. Exception listed below...
2019-11-22T17:08:47.5745486Z Error, System.IO.FileLoadException: Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior. ---> System.IO.FileNotFoundException: Could not find file '/home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/nopt'.
2019-11-22T17:08:47.5746112Z File name: '/home/agent/_work/1/flink_cache/flink-runtime-web/web-dashboard/node_modules/.bin/nopt'
2019-11-22T17:08:47.5746346Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2019-11-22T17:08:47.5746443Z    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2019-11-22T17:08:47.5746575Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-11-22T17:08:47.5746717Z    at Microsoft.VisualStudio.Services.Content.Common.FileStreamUtils.OpenFileStreamForAsync(String filePath, FileMode mode, FileAccess fileAccess, FileShare fileShare, FileOptions extraOptions)
2019-11-22T17:08:47.5746850Z    at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.CreateFromFileAsync(IFileSystem fileSystem, String path, CancellationToken cancellationToken, Boolean configureAwait)
2019-11-22T17:08:47.5747057Z    at Microsoft.VisualStudio.Services.BlobStore.Common.FileBlobDescriptor.CalculateAsync(IFileSystem fileSystem, String rootDirectory, Boolean chunkDedup, String relativePath, FileBlobType fileBlobType, CancellationToken cancellationToken)
2019-11-22T17:08:47.5747206Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
2019-11-22T17:08:47.5747375Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
2019-11-22T17:08:47.5747555Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass25_0.<<PaginateAndProcessFilesHelperAsync>b__0>d.MoveNext()
2019-11-22T17:08:47.5748107Z --- End of stack trace from previous location where exception was thrown ---
2019-11-22T17:08:47.5748257Z    at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
2019-11-22T17:08:47.5748515Z --- End of stack trace from previous location where exception was thrown ---
2019-11-22T17:08:47.5748702Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.PaginateAndProcessFilesHelperAsync(String sourceDirectory, Boolean chunkDedup, IEnumerable`1 pathsInDir, Action`1 hashCompleteCallback, Int32 currentPage, Int32 totalPages, CancellationToken cancellationToken)
2019-11-22T17:08:47.5748847Z    at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass22_0.<<PaginateAndProcessFiles>b__1>d.MoveNext()
2019-11-22T17:08:47.6819289Z Information, 100 out of 104208 files processed (Group: 114/1043)
2019-11-22T17:08:47.7651668Z Information, 200 out of 104208 files processed (Group: 117/1043)
2019-11-22T17:08:47.9333829Z Information, 300 out of 104208 files processed (Group: 67/1043)
2019-11-22T17:08:47.9433159Z Information, 400 out of 104208 files processed (Group: 99/1043)
2019-11-22T17:08:48.7825995Z Information, 500 out of 104208 files processed (Group: 96/1043)
2019-11-22T17:08:48.8368698Z Information, 600 out of 104208 files processed (Group: 87/1043)
2019-11-22T17:08:48.8416320Z Information, 800 out of 104208 files processed (Group: 85/1043)
2019-11-22T17:08:48.8432001Z Information, 700 out of 104208 files processed (Group: 128/1043)
2019-11-22T17:08:48.8439930Z Information, 1100 out of 104208 files processed (Group: 112/1043)
2019-11-22T17:08:48.8473147Z Information, 900 out of 104208 files processed (Group: 103/1043)
2019-11-22T17:08:48.8476280Z Information, 1200 out of 104208 files processed (Group: 126/1043)
2019-11-22T17:08:48.8489043Z Information, 1000 out of 104208 files processed (Group: 116/1043)
2019-11-22T17:08:48.8515988Z Information, 1300 out of 104208 files processed (Group: 119/1043)
2019-11-22T17:08:48.8625773Z Information, 1400 out of 104208 files processed (Group: 102/1043)
2019-11-22T17:08:48.8680600Z Information, 1500 out of 104208 files processed (Group: 125/1043)
2019-11-22T17:08:48.8715801Z Information, 2000 out of 104208 files processed (Group: 113/1043)
2019-11-22T17:08:48.8719270Z Information, 1700 out of 104208 files processed (Group: 93/1043)
2019-11-22T17:08:48.8721299Z Information, 1900 out of 104208 files processed (Group: 104/1043)
2019-11-22T17:08:48.8721852Z Information, 2300 out of 104208 files processed (Group: 98/1043)
2019-11-22T17:08:48.8732261Z Information, 2200 out of 104208 files processed (Group: 120/1043)
2019-11-22T17:08:48.8732603Z Information, 2100 out of 104208 files processed (Group: 90/1043)
2019-11-22T17:08:48.8735901Z Information, 1600 out of 104208 files processed (Group: 124/1043)
2019-11-22T17:08:48.8740019Z Information, 2400 out of 104208 files processed (Group: 68/1043)
2019-11-22T17:08:48.8752458Z Information, 2500 out of 104208 files processed (Group: 123/1043)
2019-11-22T17:08:48.8779852Z Information, 1800 out of 104208 files processed (Group: 127/1043)
2019-11-22T17:08:48.8783158Z Information, 2600 out of 104208 files processed (Group: 110/1043)
2019-11-22T17:08:48.8805096Z Information, 2700 out of 104208 files processed (Group: 122/1043)
2019-11-22T17:08:48.8805393Z Information, 2800 out of 104208 files processed (Group: 111/1043)
2019-11-22T17:08:48.8907650Z Information, 2900 out of 104208 files processed (Group: 107/1043)
2019-11-22T17:08:48.9056808Z Information, 3000 out of 104208 files processed (Group: 23/1043)
2019-11-22T17:08:48.9060212Z Information, 3100 out of 104208 files processed (Group: 4/1043)
2019-11-22T17:08:48.9076179Z Information, 3200 out of 104208 files processed (Group: 121/1043)
2019-11-22T17:08:48.9099073Z Information, 3300 out of 104208 files processed (Group: 13/1043)
2019-11-22T17:08:48.9117990Z Information, 3400 out of 104208 files processed (Group: 115/1043)
2019-11-22T17:08:48.9186324Z Information, 3500 out of 104208 files processed (Group: 21/1043)
2019-11-22T17:08:48.9316126Z Information, 3600 out of 104208 files processed (Group: 5/1043)
2019-11-22T17:08:48.9318974Z Information, 3700 out of 104208 files processed (Group: 26/1043)
2019-11-22T17:08:48.9319214Z Information, 3800 out of 104208 files processed (Group: 95/1043)
2019-11-22T17:08:48.9336427Z Information, 3900 out of 104208 files processed (Group: 24/1043)
2019-11-22T17:08:48.9336799Z Information, 4000 out of 104208 files processed (Group: 30/1043)
2019-11-22T17:08:48.9340114Z Information, 4300 out of 104208 files processed (Group: 9/1043)
2019-11-22T17:08:48.9356819Z Information, 4200 out of 104208 files processed (Group: 1/1043)
2019-11-22T17:08:48.9359860Z Information, 4700 out of 104208 files processed (Group: 2/1043)
2019-11-22T17:08:48.9364542Z Information, 4700 out of 104208 files processed (Group: 32/1043)
2019-11-22T17:08:48.9364704Z Information, 4100 out of 104208 files processed (Group: 29/1043)
2019-11-22T17:08:48.9365211Z Information, 4500 out of 104208 files processed (Group: 16/1043)
2019-11-22T17:08:48.9365345Z Information, 4400 out of 104208 files processed (Group: 19/1043)
2019-11-22T17:08:48.9365520Z Information, 4800 out of 104208 files processed (Group: 11/1043)
2019-11-22T17:08:48.9365652Z Information, 4900 out of 104208 files processed (Group: 27/1043)
2019-11-22T17:08:48.9365829Z Information, 5000 out of 104208 files processed (Group: 8/1043)
2019-11-22T17:08:48.9390005Z Information, 5100 out of 104208 files processed (Group: 10/1043)
2019-11-22T17:08:48.9440807Z Information, 5300 out of 104208 files processed (Group: 17/1043)
2019-11-22T17:08:48.9448358Z Information, 5200 out of 104208 files processed (Group: 14/1043)
2019-11-22T17:08:48.9453716Z Information, 5400 out of 104208 files processed (Group: 7/1043)
2019-11-22T17:08:48.9468381Z Information, 5500 out of 104208 files processed (Group: 3/1043)
2019-11-22T17:08:48.9577510Z Information, 5600 out of 104208 files processed (Group: 31/1043)
2019-11-22T17:08:48.9645658Z Information, 5700 out of 104208 files processed (Group: 12/1043)
2019-11-22T17:08:48.9646854Z Information, 5800 out of 104208 files processed (Group: 25/1043)
2019-11-22T17:08:48.9646948Z Information, 5900 out of 104208 files processed (Group: 28/1043)
2019-11-22T17:08:48.9647337Z Information, 6000 out of 104208 files processed (Group: 18/1043)
2019-11-22T17:08:48.9664167Z Information, 6100 out of 104208 files processed (Group: 20/1043)
2019-11-22T17:08:48.9675475Z Information, 6300 out of 104208 files processed (Group: 22/1043)
2019-11-22T17:08:48.9676286Z Information, 6500 out of 104208 files processed (Group: 75/1043)
2019-11-22T17:08:48.9679779Z Information, 6200 out of 104208 files processed (Group: 6/1043)
2019-11-22T17:08:48.9685398Z Information, 6400 out of 104208 files processed (Group: 78/1043)
2019-11-22T17:08:48.9685652Z Information, 6600 out of 104208 files processed (Group: 69/1043)
2019-11-22T17:08:48.9690218Z Information, 6700 out of 104208 files processed (Group: 83/1043)
2019-11-22T17:08:48.9701685Z Information, 6800 out of 104208 files processed (Group: 86/1043)
2019-11-22T17:08:48.9709304Z Information, 7000 out of 104208 files processed (Group: 76/1043)
2019-11-22T17:08:48.9725117Z Information, 7100 out of 104208 files processed (Group: 88/1043)
2019-11-22T17:08:48.9883685Z Information, 7100 out of 104208 files processed (Group: 38/1043)
2019-11-22T17:08:48.9956790Z Information, 7200 out of 104208 files processed (Group: 74/1043)
2019-11-22T17:08:48.9999540Z Information, 7500 out of 104208 files processed (Group: 81/1043)
2019-11-22T17:08:49.0004792Z Information, 7600 out of 104208 files processed (Group: 82/1043)
2019-11-22T17:08:49.0005165Z Information, 7800 out of 104208 files processed (Group: 80/1043)
2019-11-22T17:08:49.0005303Z Information, 7300 out of 104208 files processed (Group: 41/1043)
2019-11-22T17:08:49.0005481Z Information, 7500 out of 104208 files processed (Group: 77/1043)
2019-11-22T17:08:49.0007266Z Information, 7800 out of 104208 files processed (Group: 73/1043)
2019-11-22T17:08:49.0008013Z Information, 8000 out of 104208 files processed (Group: 37/1043)
2019-11-22T17:08:49.0020479Z Information, 8000 out of 104208 files processed (Group: 89/1043)
2019-11-22T17:08:49.0020884Z Information, 8100 out of 104208 files processed (Group: 79/1043)
2019-11-22T17:08:49.0025566Z Information, 8300 out of 104208 files processed (Group: 43/1043)
2019-11-22T17:08:49.0030612Z Information, 8200 out of 104208 files processed (Group: 71/1043)
2019-11-22T17:08:49.0034213Z Information, 8400 out of 104208 files processed (Group: 64/1043)
2019-11-22T17:08:49.0100783Z Information, 8500 out of 104208 files processed (Group: 72/1043)
2019-11-22T17:08:49.0150117Z Information, 8600 out of 104208 files processed (Group: 35/1043)
2019-11-22T17:08:49.0208073Z Information, 8700 out of 104208 files processed (Group: 15/1043)
2019-11-22T17:08:49.0318120Z Information, 8900 out of 104208 files processed (Group: 70/1043)
2019-11-22T17:08:49.0320817Z Information, 9100 out of 104208 files processed (Group: 84/1043)
2019-11-22T17:08:49.0321454Z Information, 9000 out of 104208 files processed (Group: 33/1043)
2019-11-22T17:08:49.0321592Z Information, 9600 out of 104208 files processed (Group: 63/1043)
2019-11-22T17:08:49.0321778Z Information, 9400 out of 104208 files processed (Group: 97/1043)
2019-11-22T17:08:49.0321913Z Information, 8800 out of 104208 files processed (Group: 58/1043)
2019-11-22T17:08:49.0322118Z Information, 9600 out of 104208 files processed (Group: 56/1043)
2019-11-22T17:08:49.0322264Z Information, 9700 out of 104208 files processed (Group: 49/1043)
2019-11-22T17:08:49.0387774Z Information, 9200 out of 104208 files processed (Group: 36/1043)
2019-11-22T17:08:49.0388112Z Information, 9300 out of 104208 files processed (Group: 34/1043)
2019-11-22T17:08:49.0388399Z Information, 9800 out of 104208 files processed (Group: 105/1043)
2019-11-22T17:08:49.0388631Z Information, 9900 out of 104208 files processed (Group: 101/1043)
2019-11-22T17:08:49.0389000Z Information, 10000 out of 104208 files processed (Group: 100/1043)
2019-11-22T17:08:49.0389434Z Information, 10100 out of 104208 files processed (Group: 39/1043)
2019-11-22T17:08:49.0575588Z Information, 10200 out of 104208 files processed (Group: 48/1043)
2019-11-22T17:08:49.0576087Z Information, 10400 out of 104208 files processed (Group: 45/1043)
2019-11-22T17:08:49.0576397Z Information, 10500 out of 104208 files processed (Group: 47/1043)
2019-11-22T17:08:49.0576593Z Information, 10700 out of 104208 files processed (Group: 66/1043)
2019-11-22T17:08:49.0675699Z Information, 10600 out of 104208 files processed (Group: 51/1043)
2019-11-22T17:08:49.0698715Z Information, 10800 out of 104208 files processed (Group: 50/1043)
2019-11-22T17:08:49.0732388Z Information, 11000 out of 104208 files processed (Group: 106/1043)
2019-11-22T17:08:49.0739287Z Information, 11100 out of 104208 files processed (Group: 40/1043)
2019-11-22T17:08:49.0739660Z Information, 11200 out of 104208 files processed (Group: 61/1043)
2019-11-22T17:08:49.0739923Z Information, 11300 out of 104208 files processed (Group: 94/1043)
2019-11-22T17:08:49.0744202Z Information, 10300 out of 104208 files processed (Group: 91/1043)
2019-11-22T17:08:49.0744580Z Information, 11400 out of 104208 files processed (Group: 62/1043)
2019-11-22T17:08:49.0746123Z Information, 10900 out of 104208 files processed (Group: 44/1043)
2019-11-22T17:08:49.0746680Z Information, 11500 out of 104208 files processed (Group: 109/1043)
2019-11-22T17:08:49.0790752Z Information, 11600 out of 104208 files processed (Group: 53/1043)
2019-11-22T17:08:49.0849270Z Information, 11700 out of 104208 files processed (Group: 57/1043)
2019-11-22T17:08:49.0849631Z Information, 11800 out of 104208 files processed (Group: 42/1043)
2019-11-22T17:08:49.0850120Z Information, 11900 out of 104208 files processed (Group: 59/1043)
2019-11-22T17:08:49.0850351Z Information, 12000 out of 104208 files processed (Group: 52/1043)
2019-11-22T17:08:49.0850964Z Information, 12100 out of 104208 files processed (Group: 108/1043)
2019-11-22T17:08:49.0853140Z Information, 12200 out of 104208 files processed (Group: 118/1043)
2019-11-22T17:08:49.0853351Z Information, 12300 out of 104208 files processed (Group: 60/1043)
2019-11-22T17:08:49.0853450Z Information, 12400 out of 104208 files processed (Group: 92/1043)
2019-11-22T17:08:49.0853792Z Information, 12500 out of 104208 files processed (Group: 65/1043)
2019-11-22T17:08:49.0854143Z Information, 12600 out of 104208 files processed (Group: 46/1043)
2019-11-22T17:08:49.9969378Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 3a398cea-fe82-4283-b172-34a9e4499501
2019-11-22T17:08:50.0035828Z ##[error]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
2019-11-22T17:08:50.0259891Z ##[section]Finishing: PublishPipelineArtifact
```

**Comment by rmetzger** [comment]
Looks like the path is different on different agents:

```
Uploading pipeline artifact from /home/vsts/work/1/flink_cache for build #2539
Uploading pipeline artifact from /home/agent/_work/1/flink_cache for build #2544
```
https://dev.azure.com/rmetzger/Flink/_build/results?buildId=2539&view=logs&j=95346e54-6eaa-5d2e-3658-f54e137fcc85&t=5ec589a2-b508-56ce-f0bc-145ad5911934
https://dev.azure.com/rmetzger/Flink/_build/results?buildId=2544&view=logs&j=0b6f4d73-b90a-5b0c-8dd2-0a6ffa85c3c4&t=5d4dc765-6b4f-5976-543d-b9f12212f10f

**Comment by rmetzger** [comment]
upload on `CommunityCITest001-second` from `/home/agent2/myagent/_work/2/flink_cache` works fine.
upload on `CommunityCITest002` from `/home/agent/_work/1/flink_cache` has mentioned issue.
upload on `CommunityCITest001 ` from `/home/agent/_work/1/flink_cache` has mentioned issue.
upload on `CommunityCITest002-second` has mentioned issue.

**Comment by rmetzger** [comment]
`CommunityCITest001` is supposed to be fixed now
