### ISSUE TITLE
Artifact FlinkCompileCacheDir already exists for build 2539.

### ISSUE THREAD

**Issue by rmetzger** [rmetzger/azure-pipelines-work#2]
```
Warning, [] Try 1/3, non-retryable exception caught. Throwing. Details:
No LastRequestResponse on exception ArtifactExistsException: Artifact FlinkCompileCacheDir already exists for build 2539. Microsoft.TeamFoundation.Build.WebApi.ArtifactExistsException: Artifact FlinkCompileCacheDir already exists for build 2539.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Agent.Plugins.PipelineArtifact.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 6ade7ddd-703c-40a3-b339-ab7ea62ac5f1
##[error]Artifact FlinkCompileCacheDir already exists for build 2539.
```

**Comment by rmetzger** [comment]
Potential fix https://github.com/rmetzger/flink/commit/ab609db0a11abb1ea44e6810f01bb87008248f97
